[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311", "py312"]

[tool.coverage.run]
branch = true
source = ["guess"]
omit = ["tests/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true
