name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint
        run: |
          python -m flake8 guess
          python -m pylint guess
          python -m black --check guess tests

      - name: Tests with coverage
        run: |
          python -m coverage run -m unittest discover -s tests -p "test_*.py"
          python -m coverage report -m --fail-under=90
          python -m coverage html
